"""部门数据隔离:role_dept/created_by/project关系

Revision ID: 1560808cdb62
Revises: bc5a75bf317f
Create Date: 2026-07-13 11:01:44.418516
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1560808cdb62"
down_revision: Union[str, None] = "bc5a75bf317f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_dept",
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.Column("dept_id", sa.Integer(), nullable=False, comment="部门ID(自定义数据范围)"),
        sa.ForeignKeyConstraint(
            ["dept_id"],
            ["department.id"],
            name=op.f("fk_role_dept_dept_id_department"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_role_dept_role_id_role"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "dept_id", name=op.f("pk_role_dept")),
    )
    op.add_column(
        "alarm",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(op.f("ix_alarm_created_by"), "alarm", ["created_by"], unique=False)
    op.create_index(op.f("ix_alarm_project_id"), "alarm", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_alarm_created_by_user"),
        "alarm",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "anti_intrusion_device",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(
        op.f("ix_anti_intrusion_device_created_by"),
        "anti_intrusion_device",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anti_intrusion_device_project_id"),
        "anti_intrusion_device",
        ["project_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_anti_intrusion_device_created_by_user"),
        "anti_intrusion_device",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "electronic_fence",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(
        op.f("ix_electronic_fence_created_by"), "electronic_fence", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_electronic_fence_project_id"), "electronic_fence", ["project_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_electronic_fence_created_by_user"),
        "electronic_fence",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "locate_device",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(
        op.f("ix_locate_device_created_by"), "locate_device", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_locate_device_project_id"), "locate_device", ["project_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_locate_device_created_by_user"),
        "locate_device",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "machine",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(op.f("ix_machine_created_by"), "machine", ["created_by"], unique=False)
    op.create_index(op.f("ix_machine_project_id"), "machine", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_machine_created_by_user"),
        "machine",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "person",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(op.f("ix_person_created_by"), "person", ["created_by"], unique=False)
    op.create_index(op.f("ix_person_project_id"), "person", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_person_created_by_user"),
        "person",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "project",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(op.f("ix_project_created_by"), "project", ["created_by"], unique=False)
    op.create_index(op.f("ix_project_dept_id"), "project", ["dept_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_project_created_by_user"),
        "project",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "role",
        "data_scope",
        existing_type=sa.INTEGER(),
        comment="数据权限范围(1=全部 2=自定义部门(含下级) 3=本部门及以下 4=仅本人)",
        existing_comment="数据权限范围(1=全部 2=自定义部门 3=本部门 4=仅本人)",
        existing_nullable=False,
    )
    op.add_column(
        "train_approach_device",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(
        op.f("ix_train_approach_device_created_by"),
        "train_approach_device",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_train_approach_device_project_id"),
        "train_approach_device",
        ["project_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_train_approach_device_created_by_user"),
        "train_approach_device",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "work_plan",
        sa.Column("created_by", sa.Integer(), nullable=True, comment="创建人ID(数据范围-仅本人)"),
    )
    op.create_index(op.f("ix_work_plan_created_by"), "work_plan", ["created_by"], unique=False)
    op.create_index(op.f("ix_work_plan_project_id"), "work_plan", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_work_plan_created_by_user"),
        "work_plan",
        "user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_work_plan_created_by_user"), "work_plan", type_="foreignkey")
    op.drop_index(op.f("ix_work_plan_project_id"), table_name="work_plan")
    op.drop_index(op.f("ix_work_plan_created_by"), table_name="work_plan")
    op.drop_column("work_plan", "created_by")
    op.drop_constraint(
        op.f("fk_train_approach_device_created_by_user"),
        "train_approach_device",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_train_approach_device_project_id"), table_name="train_approach_device")
    op.drop_index(op.f("ix_train_approach_device_created_by"), table_name="train_approach_device")
    op.drop_column("train_approach_device", "created_by")
    op.alter_column(
        "role",
        "data_scope",
        existing_type=sa.INTEGER(),
        comment="数据权限范围(1=全部 2=自定义部门 3=本部门 4=仅本人)",
        existing_comment="数据权限范围(1=全部 2=自定义部门(含下级) 3=本部门及以下 4=仅本人)",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("fk_project_created_by_user"), "project", type_="foreignkey")
    op.drop_index(op.f("ix_project_dept_id"), table_name="project")
    op.drop_index(op.f("ix_project_created_by"), table_name="project")
    op.drop_column("project", "created_by")
    op.drop_constraint(op.f("fk_person_created_by_user"), "person", type_="foreignkey")
    op.drop_index(op.f("ix_person_project_id"), table_name="person")
    op.drop_index(op.f("ix_person_created_by"), table_name="person")
    op.drop_column("person", "created_by")
    op.drop_constraint(op.f("fk_machine_created_by_user"), "machine", type_="foreignkey")
    op.drop_index(op.f("ix_machine_project_id"), table_name="machine")
    op.drop_index(op.f("ix_machine_created_by"), table_name="machine")
    op.drop_column("machine", "created_by")
    op.drop_constraint(
        op.f("fk_locate_device_created_by_user"), "locate_device", type_="foreignkey"
    )
    op.drop_index(op.f("ix_locate_device_project_id"), table_name="locate_device")
    op.drop_index(op.f("ix_locate_device_created_by"), table_name="locate_device")
    op.drop_column("locate_device", "created_by")
    op.drop_constraint(
        op.f("fk_electronic_fence_created_by_user"), "electronic_fence", type_="foreignkey"
    )
    op.drop_index(op.f("ix_electronic_fence_project_id"), table_name="electronic_fence")
    op.drop_index(op.f("ix_electronic_fence_created_by"), table_name="electronic_fence")
    op.drop_column("electronic_fence", "created_by")
    op.drop_constraint(
        op.f("fk_anti_intrusion_device_created_by_user"),
        "anti_intrusion_device",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_anti_intrusion_device_project_id"), table_name="anti_intrusion_device")
    op.drop_index(op.f("ix_anti_intrusion_device_created_by"), table_name="anti_intrusion_device")
    op.drop_column("anti_intrusion_device", "created_by")
    op.drop_constraint(op.f("fk_alarm_created_by_user"), "alarm", type_="foreignkey")
    op.drop_index(op.f("ix_alarm_project_id"), table_name="alarm")
    op.drop_index(op.f("ix_alarm_created_by"), table_name="alarm")
    op.drop_column("alarm", "created_by")
    op.drop_table("role_dept")
    # ### end Alembic commands ###
