"""初始RBAC与业务表

Revision ID: 1b84662063d2
Revises:
Create Date: 2026-07-13 10:30:42.995217
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b84662063d2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarm_config",
        sa.Column("enable_popup", sa.Boolean(), nullable=False, comment="是否弹窗"),
        sa.Column("enable_voice", sa.Boolean(), nullable=False, comment="是否语音"),
        sa.Column("voice_file", sa.String(length=255), nullable=True, comment="语音文件"),
        sa.Column("distance_machine", sa.Integer(), nullable=False, comment="大机告警间距"),
        sa.Column("distance_handheld", sa.Integer(), nullable=False, comment="人员手持机告警间距"),
        sa.Column("distance_badge", sa.Integer(), nullable=False, comment="人员工牌告警间距"),
        sa.Column("distance_band", sa.Integer(), nullable=False, comment="人员手环告警间距"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarm_config")),
    )
    op.create_table(
        "department",
        sa.Column("name", sa.String(length=64), nullable=False, comment="部门名称"),
        sa.Column("code", sa.String(length=64), nullable=False, comment="部门编码"),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="上级部门ID"),
        sa.Column("leader", sa.String(length=64), nullable=True, comment="负责人"),
        sa.Column("phone", sa.String(length=32), nullable=True, comment="联系电话"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("remark", sa.String(length=255), nullable=True, comment="备注"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="是否软删除"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["department.id"],
            name=op.f("fk_department_parent_id_department"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department")),
        sa.UniqueConstraint("code", name=op.f("uq_department_code")),
    )
    op.create_index(op.f("ix_department_parent_id"), "department", ["parent_id"], unique=False)
    op.create_table(
        "dict_data",
        sa.Column("dict_type", sa.String(length=64), nullable=False, comment="字典类型"),
        sa.Column("dict_label", sa.String(length=64), nullable=False, comment="显示名"),
        sa.Column("dict_value", sa.String(length=64), nullable=False, comment="存储值"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dict_data")),
    )
    op.create_table(
        "permission",
        sa.Column("name", sa.String(length=64), nullable=False, comment="权限名称"),
        sa.Column("code", sa.String(length=100), nullable=False, comment="权限标识"),
        sa.Column("type", sa.Integer(), nullable=False, comment="类型(1目录 2菜单 3按钮/接口)"),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="上级权限ID"),
        sa.Column("path", sa.String(length=200), nullable=True, comment="前端路由"),
        sa.Column("component", sa.String(length=200), nullable=True, comment="前端组件"),
        sa.Column("icon", sa.String(length=64), nullable=True, comment="图标"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("remark", sa.String(length=255), nullable=True, comment="备注"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="是否软删除"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["permission.id"],
            name=op.f("fk_permission_parent_id_permission"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission")),
    )
    op.create_index(op.f("ix_permission_code"), "permission", ["code"], unique=True)
    op.create_index(op.f("ix_permission_parent_id"), "permission", ["parent_id"], unique=False)
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=64), nullable=False, comment="角色名称"),
        sa.Column("code", sa.String(length=64), nullable=False, comment="角色编码"),
        sa.Column(
            "data_scope",
            sa.Integer(),
            nullable=False,
            comment="数据权限范围(1=全部 2=自定义部门 3=本部门 4=仅本人)",
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False, comment="是否系统内置(不可删除)"),
        sa.Column("remark", sa.String(length=255), nullable=True, comment="备注"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="是否软删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    op.create_index(op.f("ix_role_code"), "role", ["code"], unique=True)
    op.create_table(
        "project",
        sa.Column("dept_id", sa.Integer(), nullable=True, comment="归属部门"),
        sa.Column("name", sa.String(length=128), nullable=False, comment="项目名称"),
        sa.Column("short_name", sa.String(length=64), nullable=True, comment="项目简称"),
        sa.Column("intro", sa.String(length=1024), nullable=True, comment="项目介绍"),
        sa.Column("start_date", sa.Date(), nullable=True, comment="开工日期"),
        sa.Column("end_date", sa.Date(), nullable=True, comment="完工日期"),
        sa.Column("duration", sa.Integer(), nullable=True, comment="项目工期(天)"),
        sa.Column("mileage", sa.String(length=64), nullable=True, comment="里程"),
        sa.Column("section", sa.String(length=128), nullable=True, comment="区间"),
        sa.Column("coordinate", sa.String(length=128), nullable=True, comment="坐标"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="项目状态"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["dept_id"],
            ["department.id"],
            name=op.f("fk_project_dept_id_department"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.Column("permission_id", sa.Integer(), nullable=False, comment="权限ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="授权时间",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name=op.f("fk_role_permission_permission_id_permission"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_role_permission_role_id_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permission")),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=64), nullable=False, comment="登录账号"),
        sa.Column("nickname", sa.String(length=64), nullable=True, comment="昵称"),
        sa.Column(
            "password_hash", sa.String(length=255), nullable=False, comment="密码哈希(bcrypt)"
        ),
        sa.Column("email", sa.String(length=128), nullable=True, comment="邮箱"),
        sa.Column("phone", sa.String(length=32), nullable=True, comment="手机号"),
        sa.Column("gender", sa.String(length=8), nullable=True, comment="性别"),
        sa.Column("avatar", sa.String(length=255), nullable=True, comment="头像地址"),
        sa.Column("dept_id", sa.Integer(), nullable=True, comment="归属部门ID"),
        sa.Column("status", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column(
            "is_superuser", sa.Boolean(), nullable=False, comment="是否超级管理员(绕过权限校验)"
        ),
        sa.Column("login_fail_count", sa.Integer(), nullable=False, comment="连续登录失败次数"),
        sa.Column(
            "locked_until", sa.DateTime(timezone=True), nullable=True, comment="账户锁定截止时间"
        ),
        sa.Column(
            "last_login_at", sa.DateTime(timezone=True), nullable=True, comment="最近登录时间"
        ),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True, comment="最近登录IP"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="是否软删除"),
        sa.ForeignKeyConstraint(
            ["dept_id"],
            ["department.id"],
            name=op.f("fk_user_dept_id_department"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_dept_id"), "user", ["dept_id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "alarm",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("alarm_type", sa.String(length=32), nullable=True, comment="告警类型"),
        sa.Column("device_type", sa.String(length=32), nullable=True, comment="设备类型"),
        sa.Column("device_name", sa.String(length=128), nullable=True, comment="设备名称"),
        sa.Column("device_no", sa.String(length=64), nullable=True, comment="设备编号"),
        sa.Column("alarm_info", sa.String(length=512), nullable=True, comment="告警信息"),
        sa.Column("alarm_status", sa.String(length=16), nullable=False, comment="告警状态"),
        sa.Column("handle_status", sa.String(length=16), nullable=False, comment="处理状态"),
        sa.Column("handle_content", sa.String(length=1024), nullable=True, comment="处理内容"),
        sa.Column("alarm_time", sa.DateTime(timezone=True), nullable=True, comment="告警时间"),
        sa.Column("fence_name", sa.String(length=128), nullable=True, comment="围栏名称"),
        sa.Column("media_urls", sa.String(length=1024), nullable=True, comment="图片/视频URL"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_alarm_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarm")),
    )
    op.create_table(
        "anti_intrusion_device",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False, comment="设备名称"),
        sa.Column("device_no", sa.String(length=64), nullable=False, comment="设备编号"),
        sa.Column("sn", sa.String(length=128), nullable=True, comment="设备SN码"),
        sa.Column("longitude", sa.Float(), nullable=True, comment="经度"),
        sa.Column("latitude", sa.Float(), nullable=True, comment="纬度"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="设备状态"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_anti_intrusion_device_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anti_intrusion_device")),
        sa.UniqueConstraint("device_no", name=op.f("uq_anti_intrusion_device_device_no")),
    )
    op.create_table(
        "electronic_fence",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False, comment="围栏名称"),
        sa.Column("fence_type", sa.String(length=32), nullable=True, comment="围栏类型"),
        sa.Column("enabled", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("geometry_wkt", sa.Text(), nullable=True, comment="围栏几何(WKT)"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_electronic_fence_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_electronic_fence")),
    )
    op.create_table(
        "locate_device",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False, comment="设备名称"),
        sa.Column("device_no", sa.String(length=64), nullable=False, comment="设备编号"),
        sa.Column("device_type", sa.String(length=32), nullable=True, comment="设备类型"),
        sa.Column("function", sa.String(length=255), nullable=True, comment="设备功能"),
        sa.Column("sn", sa.String(length=128), nullable=True, comment="设备SN码"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="设备状态"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_locate_device_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locate_device")),
        sa.UniqueConstraint("device_no", name=op.f("uq_locate_device_device_no")),
    )
    op.create_table(
        "machine",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("machine_no", sa.String(length=64), nullable=False, comment="大机编号"),
        sa.Column("machine_type", sa.String(length=64), nullable=True, comment="大机类型"),
        sa.Column("spec_model", sa.String(length=128), nullable=True, comment="规格及型号"),
        sa.Column("description", sa.String(length=512), nullable=True, comment="大机设备说明"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_machine_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_machine")),
    )
    op.create_table(
        "person",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("person_no", sa.String(length=64), nullable=False, comment="人员工号"),
        sa.Column("name", sa.String(length=64), nullable=False, comment="姓名"),
        sa.Column("gender", sa.String(length=8), nullable=True, comment="性别"),
        sa.Column("phone", sa.String(length=32), nullable=True, comment="电话"),
        sa.Column("person_type", sa.String(length=32), nullable=True, comment="人员类型"),
        sa.Column("icon", sa.String(length=255), nullable=True, comment="人员图标"),
        sa.Column("device_no", sa.String(length=64), nullable=True, comment="绑定设备编号"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_person_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person")),
    )
    op.create_table(
        "train_approach_device",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False, comment="设备名称"),
        sa.Column("device_no", sa.String(length=64), nullable=False, comment="设备编号"),
        sa.Column("sn", sa.String(length=128), nullable=True, comment="设备SN码"),
        sa.Column("direction", sa.String(length=32), nullable=True, comment="设备方位"),
        sa.Column("longitude", sa.Float(), nullable=True, comment="经度"),
        sa.Column("latitude", sa.Float(), nullable=True, comment="纬度"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="设备状态"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_train_approach_device_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_train_approach_device")),
        sa.UniqueConstraint("device_no", name=op.f("uq_train_approach_device_device_no")),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户ID"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="授权时间",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_user_role_role_id_role"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_role_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_role")),
    )
    op.create_table(
        "work_plan",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False, comment="计划名称"),
        sa.Column("is_start", sa.Boolean(), nullable=False, comment="计划启动"),
        sa.Column("description", sa.String(length=1024), nullable=True, comment="计划说明"),
        sa.Column("plan_time", sa.String(length=255), nullable=True, comment="计划时间"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="计划状态"),
        sa.Column("rule_json", sa.Text(), nullable=True, comment="规则配置(JSON)"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_work_plan_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_plan")),
    )
    op.create_table(
        "work_plan_device",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.String(length=32), nullable=False, comment="设备类型"),
        sa.Column("device_no", sa.String(length=64), nullable=False, comment="设备编号"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["work_plan.id"],
            name=op.f("fk_work_plan_device_plan_id_work_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "plan_id", "device_type", "device_no", "id", name=op.f("pk_work_plan_device")
        ),
    )
    op.create_table(
        "work_plan_fence",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("fence_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["fence_id"],
            ["electronic_fence.id"],
            name=op.f("fk_work_plan_fence_fence_id_electronic_fence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["work_plan.id"],
            name=op.f("fk_work_plan_fence_plan_id_work_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plan_id", "fence_id", "id", name=op.f("pk_work_plan_fence")),
    )
    op.create_table(
        "work_plan_machine",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machine.id"],
            name=op.f("fk_work_plan_machine_machine_id_machine"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["work_plan.id"],
            name=op.f("fk_work_plan_machine_plan_id_work_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plan_id", "machine_id", "id", name=op.f("pk_work_plan_machine")),
    )
    op.create_table(
        "work_plan_person",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_work_plan_person_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["work_plan.id"],
            name=op.f("fk_work_plan_person_plan_id_work_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plan_id", "person_id", "id", name=op.f("pk_work_plan_person")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("work_plan_person")
    op.drop_table("work_plan_machine")
    op.drop_table("work_plan_fence")
    op.drop_table("work_plan_device")
    op.drop_table("work_plan")
    op.drop_table("user_role")
    op.drop_table("train_approach_device")
    op.drop_table("person")
    op.drop_table("machine")
    op.drop_table("locate_device")
    op.drop_table("electronic_fence")
    op.drop_table("anti_intrusion_device")
    op.drop_table("alarm")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_dept_id"), table_name="user")
    op.drop_table("user")
    op.drop_table("role_permission")
    op.drop_table("project")
    op.drop_index(op.f("ix_role_code"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_permission_parent_id"), table_name="permission")
    op.drop_index(op.f("ix_permission_code"), table_name="permission")
    op.drop_table("permission")
    op.drop_table("dict_data")
    op.drop_index(op.f("ix_department_parent_id"), table_name="department")
    op.drop_table("department")
    op.drop_table("alarm_config")
    # ### end Alembic commands ###
