"""role表补充status列

Revision ID: bc5a75bf317f
Revises: 1b84662063d2
Create Date: 2026-07-13 10:32:05.273350
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc5a75bf317f"
down_revision: Union[str, None] = "1b84662063d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("role", sa.Column("status", sa.Boolean(), nullable=False, comment="是否启用"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role", "status")
    # ### end Alembic commands ###
